title: M.Erkan Çam
description: > # this means to ignore newlines until "baseurl:"
  Mustafa Erkan Çam - Personal Blog 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: M.Erkan Çam # add your name
author-img: erkan-cam.jpg # add your photo
about-author:  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: merkancam # add your Github handle
social-linkedin: merkancam # add your Linkedin handle
social-email: merkancam@gmail.com # add your Email address

# Disqus
discus-identifier: https-merkancam-github-io

# Tracker
analytics: UA-160044976-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
